export const arr = [
    {
        user: "Greg",
        user_img: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 1,
        children: 1,
        activity: 2,
        gender: 3,
        age: 8,
        stay: 1,
    },
    {
        user: "Mary",
        user_img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 1,
        children: 2,
        activity: 3,
        gender: 1,
        age: 2,
        stay: 4,
    },
    {
        user: "Todd",
        user_img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 3,
        children: 2,
        activity: 1,
        gender: 2,
        age: 3,
        stay: 2,
    },
    {
        user: "Lori",
        user_img: "https://images.unsplash.com/photo-1611590027211-b954fd027b51",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 1,
        children: 1,
        activity: 5,
        gender: 1,
        age: 6,
        stay: 1,
    },
    {
        user: "Pete",
        user_img: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 2,
        children: 2,
        activity: 4,
        gender: 3,
        age: 4,
        stay: 2,
    },

    {
        user: "Tara",
        user_img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 1,
        children: 2,
        activity: 3,
        gender: 2,
        age:7,
        stay: 4,
    },

    {
        user: "Otto",
        user_img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 2,
        children: 2,
        activity: 2,
        gender: 1,
        age: 5,
        stay: 3,
    },
    {
        user: "Milly",
        user_img: "https://images.unsplash.com/photo-1614283233556-f35b0c801ef1",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 3,
        children: 2,
        activity: 1,
        gender: 3,
        age: 1,
        stay: 2,
    },
    {
        user: "Kile",
        user_img: "https://images.unsplash.com/photo-1517070208541-6ddc4d3efbcb",
        country: "Chile",
        city: "Santiago",
        start_date: "1/1/1",
        end_date: "2/2/2",
        traveling: 3,
        children: 1,
        activity: 5,
        gender: 2,
        age: 2,
        stay: 3,
    },

    {   
        user: "Dude",
        country: "Argentina",
        city: "Buenos Aires",
        start_date: "3/3/3",
        end_date: "4/4/4"
    },
    {
        user: "Babe",
        country: "Brazil",
        city: "Brasilia",
        start_date: "5/5/5",
        end_date: "6/6/6"
    }
]